dia= input('Digite o dia do seu nascimento: ')
mes= input('Digite o mês do seu nascimento: ')
ano= input('Digite o ano do seu nascimento: ')
print('Você nasceu no dia',dia,'de',mes,'do ano de',ano,'. Correto?')
input ()
